In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
#preprocessing of data
df=pd.read_csv("Churn_Modelling.csv")
x=df.iloc[:,3:-1].values #Taking colums from credit score to the second last column
y=df.iloc[:,-1].values

In [6]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [7]:
print(y)

[1 0 1 ... 1 1 0]


In [9]:
#labelling of data
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])   #encoding the gender column
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [11]:
#On hot encoding : This will change the alphabetical data into numeric data , which is easily understandable by machine
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough') #changing the country column
x=np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 1.0 ... 1 1 101348.88]
 [1.0 0.0 0.0 ... 0 1 112542.58]
 [1.0 0.0 1.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 1.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 1.0 ... 1 0 38190.78]]


In [13]:
#splitting the data into training and test dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x, y, test_size = 0.2, random_state = 0) #20% for test case


In [15]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [16]:
#ANN modelling
ann = tf.keras.models.Sequential()

In [17]:
#Adding input layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
#Adding 2nd hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [18]:
#Output value
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid')) #sigmoid will change all the values bw 0 to1


Compiling the ANN


In [19]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [21]:
ann.fit(x_train,y_train,batch_size=5,epochs=50)

Epoch 1/50
1600/1600 [==============================] - 5s 3ms/step - loss: 0.3458 - accuracy: 0.8580
Epoch 2/50
1600/1600 [==============================] - 6s 4ms/step - loss: 0.3449 - accuracy: 0.8591
Epoch 3/50
1600/1600 [==============================] - 5s 3ms/step - loss: 0.3435 - accuracy: 0.8572
Epoch 4/50
1600/1600 [==============================] - 9s 6ms/step - loss: 0.3420 - accuracy: 0.8602
Epoch 5/50
1600/1600 [==============================] - 3s 2ms/step - loss: 0.3413 - accuracy: 0.8622
Epoch 6/50
1600/1600 [==============================] - 3s 2ms/step - loss: 0.3410 - accuracy: 0.8615
Epoch 7/50
1600/1600 [==============================] - 3s 2ms/step - loss: 0.3402 - accuracy: 0.8637
Epoch 8/50
1600/1600 [==============================] - 4s 2ms/step - loss: 0.3400 - accuracy: 0.8620
Epoch 9/50
1600/1600 [==============================] - 3s 2ms/step - loss: 0.3400 - accuracy: 0.8605
Epoch 10/50
1600/1600 [==============================] - 3s 2ms/step - loss: 0.339

In [25]:
#predicting that a customer will stay or go:
print(ann.predict(sc.transform([[1, 0, 1, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)
#we put all the vlues of different columns and get the probabalilty , if prob >0.5 then it is true

ValueError: X has 12 features, but StandardScaler is expecting 13 features as input.